name: app-next-postgres

services:
  db:
    build:
      context: ../ #Поднимаемся на одну папку вверх! важно докер копирует файлы относительно контекста только вниз !!!!!!!
      dockerfile: ./dev.config/Dockerfile.db
    restart: always
    # environment:
    #   - POSTGRESS_USER=postgres
    #   - POSTGRES_PASSWORD=12345
    #   - POSTGRES_DB=postgres
    #   - POSTGRESS_HOST=172.20.0.4
    volumes:
      - ../postgresql/db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      app-network:
        ipv4_address: 172.16.0.4
  app:
    build:
      context: ../tasks
      dockerfile: ../dev.config/Dockerfile.next
    depends_on:
      - db
    ports:
      - 3001:3001
    develop:
      watch:
        - path: ../tasks
          target: /usr/src/app
          action: sync+restart
    environment:
      - ENV TZ:"Europe/Moscow"
      - ENV TZ:$(cat /etc/timezone)
    networks:
      app-network:
        ipv4_address: 172.16.0.5
    volumes: #Синхронизация времени с хостом
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

networks:
  app-network:
    ipam:
      config:
        - subnet: 172.16.0.0/24

volumes:
  db_data:
  timezone:
  localtime:
