FROM postgres:16.3-alpine3.20

EXPOSE 5432

COPY ../postgresql/init.sql /docker-entrypoint-initdb.d/

ENV TZ "Europe/Moscow"
ENV POSTGRES_DB tasksdb
ENV POSTGRES_USER taskuser
ENV POSTGRES_PASSWORD 12345
ENV PGDATA=/var/lib/postgresql/data

VOLUME [ "./postgresql/db_data" ]